Elec 127
csesoc/CSElectives pull request #39
Opened 2021-09-04 15:43 UTC by timmy-huang

Made code pretty uwu

2021-09-04 15:45 UTC, hayeselnut requested changes

2021-09-04 15:45 UTC, hayeselnut commented on src/components/dropdown-sort-menu.js
> +const DropdownSort = (props) => {
rename component or file to match

2021-09-04 15:45 UTC, hayeselnut commented on src/pages/home-page.js
> +console.log(majorOptions);
remove console.log

2021-09-04 15:51 UTC, hayeselnut requested changes

2021-09-04 15:51 UTC, hayeselnut commented on src/pages/home-page.js
> +const createDropdownOption = (Item) => {
Lowercase

2021-09-05 06:39 UTC, timmy-huang commented
I think i have fixed everything but it still says changes requested im not sure what to do

2021-09-05 11:42 UTC, hayeselnut requested changes
lint

2021-09-05 11:47 UTC, hayeselnut approved these changes
finally

2021-09-05 11:48 UTC, merged